### ISSUE TITLE
The system saves new article with wrong tag, and creates new record in database

### ISSUE THREAD

**Issue by romanromanenko** [verbumby/verbum#1]
### Steps:

1. Log in as administrator;
1. Go to tab "Articles";
1. Choose dictionary "ololo";
1. In field "Content" enter the following:
    ```
    <h-hw>fweovwoif</h-hw> 12124
    ```
1. Click "Save"; 

### Expected result:
    The system not save new article, and show message about error.

### Actual result:
    The system save new article, and create the new record in database.

#### Attachments:
![image](https://user-images.githubusercontent.com/2761212/37530597-f87924d4-294a-11e8-838c-ae2fdd87567b.png)

![image](https://user-images.githubusercontent.com/2761212/37530627-0fc0f4fa-294b-11e8-9183-11a17c717d56.png)

**Comment by ramanenka** [comment]
@romanromanenko This is fixed now as well. Please verify.
