### ISSUE TITLE
Doesn't work button "Headword"

### ISSUE THREAD

**Issue by romanromanenko** [verbumby/verbum#2]
### Steps:

1. Log in as administrator;
1. Go to tab "Articles";
1. Choose Article "Радыё";
1. In field "Content" enter the following:
```
    Радыё
```
5. select all and click the button;

### Expected result:
    <v-hw>Радыё</v-hw>

### Actual result:
    Радыё

**Comment by ramanenka** [comment]
@romanromanenko Thanks for reporting this. I've fixed it, you can verify now.
