### ISSUE TITLE
This GitHub repo: please enable Discussions

### ISSUE THREAD

**Issue by vitaly-zdanevich** [verbumby/verbum#230]
For example, I want to ask - how to make it offline? How to download?

Can I implement offline in a browser, please?

**Comment by ramanenka** [comment]
@vitaly-zdanevich I've enabled discussions.

What exactly do you want to make offline and why?

**Comment by vitaly-zdanevich** [comment]
Offline is important - when there are problems with connection.

The data is not stored in this repo?

**Comment by ramanenka** [comment]
It's stored here: https://github.com/verbumby/slouniki
